# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - 'variables.env'

#  app:
#    image: foebk/simple-spring-container
#    restart: always
#    links:
#      - db
#    env_file:
#      - 'variables.env'
