# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: tester_tool

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

#  app:
#    image: foebk/simple-spring-container
#    restart: always
#    links:
#      - db
